#ifndef FSMSTATE_H
#define FSMSTATE_H

enum CalibrationPhase {
    CALIBRATION_INIT,
    CALIBRATION_BACK_OFF,
    CALIBRATION_WAIT_RELEASE,
    CALIBRATION_WAIT_1,
    CALIBRATION_SEEK_SENSOR,
    CALIBRATION_DONE
};

enum FingerMoveState {
    FINGER_IDLE,
    FINGER_UP,
    FINGER_WAIT_AFTER_UP,
    FINGER_SLIDE,
    FINGER_WAIT_AFTER_SLIDE,
    FINGER_DOWN,
    FINGER_WAIT_AFTER_DOWN, 
    FINGER_PRESS,
    CALIBRATING_SLIDER,
    CALIBRATING_RACK,
    CALIBRATING_FINGERING,
    CALIBRATING_WAIT_AFTER_RACK,
    CALIBRATING_WAIT_AFTER_SLIDER,
};


enum DeviceState {
    IDLE,
    MOVING,
    CALIBRATING,
    ERROR
};

#endif // FSMSTATE_H
