#ifndef CALIBRATIONPHASE_H
#define CALIBRATIONPHASE_H

enum CalibrationPhase {
    CALIBRATION_INIT,
    CALIBRATION_BACK_OFF,
    CALIBRATION_WAIT_1,
    CALIBRATION_SEEK_SENSOR,
    CALIBRATION_DONE
};

#endif // CALIBRATIONPHASE_H
