#ifndef FSMSTATE_H
#define FSMSTATE_H

enum CalibrationPhase {
    CALIBRATION_INIT,
    CALIBRATION_BACK_OFF,
    CALIBRATION_WAIT_RELEASE,
    CALIBRATION_WAIT_1,
    CALIBRATION_SEEK_SENSOR,
    CALIBRATION_DONE
};

enum FingerMoveState {
    FINGER_IDLE,
    FINGER_UP,
    FINGER_SLIDE,
    FINGER_DOWN,
    FINGER_PRESS,
    CALIBRATING_SLIDER,
    CALIBRATING_RACK,
    CALIBRATING_FINGERING
};

enum DeviceState {
    IDLE,
    MOVING,
    CALIBRATING,
    ERROR
};

#endif // FSMSTATE_H
